# Generated by Django 4.1.3 on 2024-09-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmis', '0003_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='coordinates',
            field=models.TextField(),
        ),
    ]
