# Generated by Django 4.1.3 on 2024-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmis', '0004_alter_routes_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('contact', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('nature', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
